### ISSUE TITLE
When using Twig, no refresh after template change

### ISSUE THREAD

**Issue by lucasmichot** [simonjodet/gumdrop#18]
With Twig, when updating the template or a partial, the result is not refreshed.

So for generating index.html from index.html.twig, Gumdrop should check the timestamps of index.html AND the timestamps of every .twig files located in _\* folders (except _vendor)

**Comment by simonjodet** [comment]
Any change in the "_layout" folder should be detected (https://github.com/simonjodet/gumdrop/blob/master/Gumdrop/FileHandler.php#L171). Do you use another path? Subfolders of "_layout"?

**Comment by lucasmichot** [comment]
Yes "_layouts" with a s, cause I've got many and my partials are in the "_partials" folder (header, footer...)
Conf.json could maybe contain an array of these folders to check ?

**Comment by simonjodet** [comment]
I guess we could check for changes everywhere except the target folder.
