### ISSUE TITLE
No imediate refresh

### ISSUE THREAD

**Issue by lucasmichot** [simonjodet/gumdrop#20]
When using Twig, after generating some files if i delete the content of _site, I have to refresh my browser several times before I can see a fresh result for one of my page). The first refresh is a 404 error page

**Comment by simonjodet** [comment]
To avoid slowing down the PC, checksums are checked every 2 seconds. That's probably why you get a 404 on your first attempt. I could add an option to set this delay.

**Comment by lucasmichot** [comment]
There should not be any delay and no slowing as well, as the server is only refreshing one specific resource.
I am afraid there is a massive bottleneck here :
https://github.com/simonjodet/gumdrop/blob/master/Gumdrop/FileHandler.php#L185
and here :
https://github.com/simonjodet/gumdrop/blob/b0b4a1ee81da60acea73a69d0dabc5c7a611ebd9/Gumdrop/Commands/Reload.php#L39

This loop and the crc are extremely time consuming, and this is maybe the reason for choosing to implement a 2s sleep in https://github.com/simonjodet/gumdrop/blob/b0b4a1ee81da60acea73a69d0dabc5c7a611ebd9/Gumdrop/Commands/Reload.php#L45
.
There is no reason to rely on the global checksum of many source files.
The only decision to regenerate a page should be the modification time.

**Comment by simonjodet** [comment]
The checksum is here to store less data between refreshs. However, I guess I could checksum some concatenation of file names, dates (and sizes?) instead. On very heavy sites, listing continuously could still have an impact on the system so I would still think we need to add some (optional?) delay.

**Comment by lucasmichot** [comment]
Well the comparison should be done only base on filename and file modification time.
There should be not delay, but maybe an option like "refresh" (true for dev, false for prod) in the conf.json
